[project]
name = "yappo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gymnasium[box2d]>=1.2.2",
    "tensorboard>=2.20.0",
    "torch>=2.9.1",
    "wandb>=0.23.1",
]
